[server]
port = 8080
session_secret = "change-me-to-a-random-string"

[db]
host = "127.0.0.1"
port = 3306
user = "pcgw"
passwd = "pcgw"
dbname = "pcgw"

[twitter]
client_id = ""
client_secret = ""
redirect_url = "http://localhost:8080/auth/twitter/callback"

# 複数のpeercast-miインスタンスはDB上のserventテーブルで管理
