[server]
port = 8080
# session_secret: 環境変数 SESSION_SECRET で設定

[db]
host = "127.0.0.1"
port = 3307
user = "pcgw"
# passwd: 環境変数 DB_PASSWD で設定
dbname = "pcgw"

[twitter]
# client_id: 環境変数 TWITTER_CLIENT_ID で設定
# client_secret: 環境変数 TWITTER_CLIENT_SECRET で設定
redirect_url = "http://127.0.0.1:8080/auth/twitter/callback"

# 複数のpeercast-miインスタンスはDB上のserventテーブルで管理

[[yp]]
name = "0yp"
addr = "pcp://yayaue.me/"

[[yp]]
name = "SP"
addr = "pcp://bayonet.ddo.jp:7146/"

[[yp]]
name = "p@YP"
addr = "pcp://root.p-at.net/"
