services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcgw
      MYSQL_USER: pcgw
      MYSQL_PASSWORD: pcgw
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mariadb-data:
