CREATE TABLE IF NOT EXISTS users (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL DEFAULT '',
	image VARCHAR(512) NOT NULL DEFAULT '',
	twitter_id VARCHAR(255) DEFAULT NULL,
	admin TINYINT(1) NOT NULL DEFAULT 0,
	suspended TINYINT(1) NOT NULL DEFAULT 0,
	bio TEXT NOT NULL DEFAULT (''),
	notice_checked_at DATETIME(6) DEFAULT NULL,
	logged_on_at DATETIME(6) DEFAULT NULL,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	UNIQUE INDEX idx_users_twitter_id (twitter_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS servents (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT (''),
	hostname VARCHAR(255) NOT NULL,
	port INT NOT NULL,
	auth_id VARCHAR(255) NOT NULL DEFAULT '',
	passwd VARCHAR(255) NOT NULL DEFAULT '',
	priority INT NOT NULL DEFAULT 0,
	max_channels INT NOT NULL DEFAULT 0,
	enabled TINYINT(1) NOT NULL DEFAULT 0,
	agent VARCHAR(255) NOT NULL DEFAULT '',
	yellow_pages VARCHAR(255) NOT NULL DEFAULT '',
	UNIQUE INDEX idx_servents_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channels (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	gnu_id VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	servent_id BIGINT NOT NULL,
	stream_key VARCHAR(255) NOT NULL DEFAULT '',
	last_active_at DATETIME(6) DEFAULT NULL,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	INDEX idx_channels_user_id (user_id),
	INDEX idx_channels_servent_id (servent_id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (servent_id) REFERENCES servents(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channel_infos (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	channel VARCHAR(255) NOT NULL DEFAULT '',
	genre VARCHAR(255) NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT (''),
	comment TEXT NOT NULL DEFAULT (''),
	url VARCHAR(512) NOT NULL DEFAULT '',
	stream_type VARCHAR(32) NOT NULL DEFAULT 'FLV',
	yp VARCHAR(255) NOT NULL DEFAULT '',
	channel_id BIGINT DEFAULT NULL,
	servent_id BIGINT DEFAULT NULL,
	source_name VARCHAR(255) NOT NULL DEFAULT '',
	terminated_at DATETIME(6) DEFAULT NULL,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
	INDEX idx_channel_infos_user_id (user_id),
	INDEX idx_channel_infos_channel_id (channel_id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (channel_id) REFERENCES channels(id),
	FOREIGN KEY (servent_id) REFERENCES servents(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sources (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	name VARCHAR(255) NOT NULL DEFAULT '',
	`key` VARCHAR(255) NOT NULL DEFAULT '',
	INDEX idx_sources_user_id (user_id),
	FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notices (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL DEFAULT '',
	body TEXT NOT NULL DEFAULT (''),
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
